// src/app/components/hud/status-hud.component.ts
import { Component, inject, computed } from '@angular/core';
import { GameService } from '../../services/game.service';
import { StatusHUDItemComponent } from './status-hud-item.component';
import { npcProfiles } from '../../data/npcProfiles';

const COMPANION_PORTRAITS: Record<string, string> = {
  Mecanica: '/assets/characters/mecanica/portrait.png',
  Muro: '/assets/characters/muro/portrait.png',
};

@Component({
  selector: 'app-status-hud',
  standalone: true,
  imports: [StatusHUDItemComponent],
  template: `
    <div class="flex items-start gap-8 pointer-events-none z-50">
      <!-- Player HUD -->
      <app-status-hud-item
        [hpPercent]="hpPercent()"
        [staminaPercent]="staminaPercent()"
        [sanityPercent]="sanityPercent()"
        portraitSrc="/assets/characters/mecanica/portrait.png"
      />

      <!-- Companion HUD -->
      @if (game.companion()) {
        <app-status-hud-item
          [hpPercent]="companionHpPercent()"
          [staminaPercent]="companionStaminaPercent()"
          [sanityPercent]="companionSanityPercent()"
          [portraitSrc]="companionPortrait()"
        />
      }
    </div>
  `,
})
export class StatusHUDComponent {
  readonly game = inject(GameService);

  readonly hpPercent = computed(() => (this.game.stats().hp / this.game.stats().maxHp) * 100);
  readonly sanityPercent = computed(() => this.game.stats().sanity);
  readonly staminaPercent = computed(() => this.game.stats().stamina);

  readonly companionPortrait = computed(() => {
    const c = this.game.companion();
    return c ? (COMPANION_PORTRAITS[c] || '') : '';
  });

  readonly companionHpPercent = computed(() => {
    const c = this.game.companion();
    if (!c) return 0;
    const profile = npcProfiles[c.toLowerCase()];
    return profile ? (profile.atributos.hp / profile.atributos.maxHp) * 100 : 0;
  });

  readonly companionStaminaPercent = computed(() => {
    const c = this.game.companion();
    if (!c) return 0;
    const profile = npcProfiles[c.toLowerCase()];
    return profile?.atributos.stamina ?? 0;
  });

  readonly companionSanityPercent = computed(() => {
    const c = this.game.companion();
    if (!c) return 0;
    const profile = npcProfiles[c.toLowerCase()];
    return profile?.atributos.sanity ?? 0;
  });
}

// src/components/hud/StatusHUD.tsx
'use client';

import { useGameStore } from '../../store/gameStore';
import StatusHUDItem from './StatusHUDItem';
import { npcProfiles } from '../../data/npcProfiles';

/**
 * StatusHUD — Top-level HUD container.
 * Renders the player's HUD and (if present) the companion's HUD side-by-side
 * floating at the top left of the screen.
 */

const COMPANION_PORTRAITS: Record<string, string> = {
  Mecanica: '/assets/characters/mecanica/portrait.png',
  Muro: '/assets/characters/muro/portrait.png',
};

export default function StatusHUD() {
  const { stats, companion } = useGameStore();

  const hpPercent = (stats.hp / stats.maxHp) * 100;
  const sanityPercent = (stats.sanity / 100) * 100;
  const staminaPercent = (stats.stamina / 100) * 100;

  let companionHpPercent = 0;
  let companionStaminaPercent = 0;
  let companionSanityPercent = 0;

  if (companion) {
    const companionId = companion.toLowerCase(); // "Mecanica" -> "mecanica"
    const profile = npcProfiles[companionId];
    if (profile && profile.atributos) {
      companionHpPercent = (profile.atributos.hp / profile.atributos.maxHp) * 100;
      companionSanityPercent = (profile.atributos.sanity / 100) * 100;
      companionStaminaPercent = (profile.atributos.stamina / 100) * 100;
    }
  }

  return (
    <div className="flex items-start gap-8 pointer-events-none z-50">
      {/* Player HUD */}
      <StatusHUDItem
        hpPercent={hpPercent}
        staminaPercent={staminaPercent}
        sanityPercent={sanityPercent}
        portraitSrc="/assets/characters/mecanica/portrait.png" // Temporary until protagonist has their own
      />

      {/* Companion HUD */}
      {companion && (
        <StatusHUDItem
          hpPercent={companionHpPercent}
          staminaPercent={companionStaminaPercent}
          sanityPercent={companionSanityPercent}
          portraitSrc={COMPANION_PORTRAITS[companion]}
        />
      )}
    </div>
  );
}
