// src/app/components/screens/game-screen.component.ts
import { Component, inject, computed, signal, OnInit, effect, untracked, output } from '@angular/core';
import { GameService } from '../../services/game.service';
import { AuthService } from '../../services/auth.service';
import { StatusHUDComponent } from '../hud/status-hud.component';
import { NarrativePanelComponent } from '../narrative/narrative-panel.component';
import { ActionPanelComponent } from '../actions/action-panel.component';
import { AIThinkingOverlayComponent } from '../actions/ai-thinking-overlay.component';
import { SettingsDialogComponent } from './settings-dialog.component';
import storyDataRaw from '../../data/storyData.json';
import { StoryNode, StoryOption, DialogueMessage } from '../../types/game';
import { npcProfiles } from '../../data/npcProfiles';

const storyData = storyDataRaw.nodes as Record<string, StoryNode>;

@Component({
  selector: 'app-game-screen',
  standalone: true,
  imports: [
    StatusHUDComponent,
    NarrativePanelComponent,
    ActionPanelComponent,
    AIThinkingOverlayComponent,
    SettingsDialogComponent
  ],
  template: `
    <div class="w-full h-full relative font-mono text-gray-300">
      
      <!-- AI Thinking Overlay — blocks all interaction -->
      @if (isProcessingFreeAction()) {
        <app-ai-thinking-overlay />
      }

      <!-- Top Controls -->
      <div class="absolute top-4 right-6 z-50 flex gap-4">
        <button 
          (click)="isSettingsOpen.set(true)"
          class="bg-[#2d372b]/80 border-2 border-[#495845] w-9 h-9 flex items-center justify-center text-gray-300 hover:bg-[#495845] hover:text-white transition-colors"
          title="Configurações"
        >
          ⚙
        </button>
        <button 
          (click)="saveGame()"
          [disabled]="auth.isLoading() || isProcessingFreeAction()"
          class="bg-[#2d372b]/80 border-2 border-[#495845] px-4 py-2 text-xs uppercase tracking-widest hover:bg-[#495845] hover:text-white transition-colors disabled:opacity-50 disabled:pointer-events-none"
        >
          [ SALVAR ] Orelhão ({{ game.payphoneTokens() }})
        </button>
      </div>

      <!-- Top Left: HUDs -->
      <div class="absolute top-4 left-6 z-50 pointer-events-none">
        <app-status-hud />
      </div>

      <!-- Main Content Area: Scene + Text -->
      <div class="absolute top-[15vh] left-6 bottom-[15vh] w-[75vw] max-w-[1400px] flex items-stretch z-10">
        
        <!-- Left Panel: Scene Image -->
        <div class="hidden md:block w-[45%] border-[4px] border-[#2b3028] border-r-0 bg-[#0d0f0c] shadow-2xl relative overflow-hidden shrink-0">
          <div class="absolute inset-0 bg-[#2d372b]/20 flex flex-col items-center justify-center text-[#495845] font-bold text-xl uppercase tracking-widest text-center px-4">
            <span>[Cena do Local]</span>
            <span class="text-sm mt-2 opacity-50">{{ currentNode()?.location || 'Desconhecido' }}</span>
          </div>

          <img 
            [src]="locationImageSrc()" 
            [alt]="currentNode()?.location" 
            class="absolute inset-0 w-full h-full object-cover z-10"
            style="image-rendering: pixelated;"
            (error)="handleImageError($event)"
          />
        </div>

        <!-- Center Panel: Narrative and Actions -->
        <div class="flex-1 flex flex-col bg-[#161815]/95 border-[4px] border-[#2b3028] shadow-2xl relative backdrop-blur-sm min-w-[500px]">
          <app-narrative-panel
            [location]="currentNode()?.location || 'Desconhecido'"
            [narrativeLog]="narrativeLog()"
          />

          <app-action-panel
            [options]="currentOptions()"
            [allowFourthOption]="currentNode()?.allowFourthOption || false"
            [loading]="isProcessingFreeAction()"
            [freeActionAttemptsRemaining]="freeActionAttemptsRemaining()"
            [freeActionMaxAttempts]="3"
            (optionClick)="handleOptionClick($event)"
            (freeAction)="handleFreeAction($event)"
          />
        </div>
      </div>

      <!-- Bottom Right: Character Full Body Sprites -->
      <div class="absolute bottom-0 right-[5%] z-20 pointer-events-none h-[50vh] flex gap-4 items-end">
        @if (currentNode()?.npcsPresentes?.includes('mecanica')) {
          <div class="relative h-full w-[30vh]">
            <img 
              src="/assets/characters/mecanica/body.png" 
              alt="Mecânica" 
              class="absolute bottom-0 w-full h-full object-contain object-bottom drop-shadow-2xl opacity-90"
              style="image-rendering: pixelated;"
            />
          </div>
        }
        @if (currentNode()?.npcsPresentes?.includes('muro') || currentNode()?.npcsPresentes?.includes('ed_fisica')) {
          <div class="relative h-full w-[30vh]">
            <img 
              src="/assets/characters/muro/body.png" 
              alt="Muro" 
              class="absolute bottom-0 w-full h-full object-contain object-bottom drop-shadow-2xl opacity-90"
              style="image-rendering: pixelated;"
            />
          </div>
        }
      </div>

      <!-- Settings Modal -->
      @if (isSettingsOpen()) {
        <app-settings-dialog
          (close)="isSettingsOpen.set(false)"
          (onReset)="handleGameReset()"
        />
      }

    </div>
  `
})
export class GameScreenComponent implements OnInit {
  readonly game = inject(GameService);
  readonly auth = inject(AuthService);

  readonly narrativeLog = signal<string[]>([]);
  readonly isProcessingFreeAction = signal(false);
  readonly freeActionAttemptsRemaining = signal(3);
  readonly isSettingsOpen = signal(false);

  readonly returnToMenu = output<void>();

  readonly currentNode = computed<StoryNode | null>(() => {
    const id = this.game.currentNodeId();
    return storyData[id] || null;
  });

  readonly currentOptions = computed(() => {
    if (this.game.isInDialogueMode() && this.game.activeNpcDialogueId()) {
      return [{ id: 'Sair', text: 'Encerrar conversa', nextId: this.game.currentNodeId() }];
    }
    const node = this.currentNode();
    return node ? node.options : [];
  });

  readonly locationImageSrc = computed(() => {
    const node = this.currentNode();
    if (!node) return '';
    if (node.image) return '/assets/locations/' + node.image;
    
    // Fallback based on slug
    const locationSlug = node.location
      .normalize("NFD")
      .replace(/[\u0300-\u036f]/g, "")
      .toLowerCase()
      .replace(/\s+/g, '-');
    return '/assets/locations/' + locationSlug + '.png';
  });

  constructor() {
    effect(() => {
      const node = this.currentNode();
      const inDialogue = this.game.isInDialogueMode();
      
      untracked(() => {
        if (node && !inDialogue) {
          this.freeActionAttemptsRemaining.set(3);
          
          const log = this.narrativeLog();
          const desc = node.baseDescription;
          if (log.length === 0 || log[log.length - 1] !== desc) {
              this.narrativeLog.update(l => [...l, desc]);
          }
        }
      });
    }, { allowSignalWrites: true });
  }

  ngOnInit() {}

  handleGameReset() {
    this.isSettingsOpen.set(false);
    this.returnToMenu.emit();
  }

  handleImageError(event: Event) {
    const img = event.target as HTMLImageElement;
    img.style.display = 'none';
  }

  async saveGame() {
    if (!this.game.usePayphoneToken()) {
      this.narrativeLog.update(l => [...l, '[- Você não tem fichas para ligar do orelhão.]']);
      return;
    }

    const currentLoc = this.currentNode()?.location || 'Desconhecido';
    const char = this.game.activeCharacter();
    const sum = '[' + new Date().toLocaleTimeString() + '] ' + char + ' em ' + currentLoc;
    
    this.game.setSaveSummary(sum);
    
    const success = await this.auth.saveGame(this.game.getState());
    if (success) {
      this.narrativeLog.update(l => [...l, '[+ Progresso salvo com sucesso no servidor.]']);
    } else {
      this.narrativeLog.update(l => [...l, '[- Falha na conexão do orelhão (Erro ao salvar).]']);
      this.game.payphoneTokens.update(t => t + 1);
    }
  }

  handleOptionClick(nextId: string) {
    const node = this.currentNode();
    if (node) {
      const clickedOption = node.options.find(o => o.nextId === nextId || o.id === nextId);
      if (clickedOption && !clickedOption.nextId && clickedOption.dialogueTarget) {
        this.game.enterDialogue(clickedOption.dialogueTarget);
        const profile = npcProfiles[clickedOption.dialogueTarget];
        this.narrativeLog.update(l => [...l, '[ Você se aproxima de ' + (profile?.codinome || clickedOption.dialogueTarget) + ' ]']);
        return;
      }
      
      if (this.game.isInDialogueMode() && nextId === node.id) {
        this.game.exitDialogue();
        this.narrativeLog.update(l => [...l, '[ Conversa encerrada. ]']);
        return;
      }
    }

    if (nextId === 'death') {
       this.game.updateStats({ hp: 0 }); 
       return;
    }
    
    this.game.goToNode(nextId);
  }

  async handleFreeAction(action: string) {
    if (this.game.isInDialogueMode()) {
      await this.handleDialogueChat(action);
      return;
    }

    if (this.freeActionAttemptsRemaining() <= 0) return;
    this.freeActionAttemptsRemaining.update(v => v - 1);
    this.narrativeLog.update(l => [...l, '> ' + action]);
    this.isProcessingFreeAction.set(true);

    try {
      const token = this.auth.token();
      const apiKey = this.auth.customGeminiKey();
      
      const reqBody: any = {
        action,
        nodeContext: this.currentNode(),
        playerStats: this.game.stats(),
        inventory: this.game.inventory(),
        playerProfile: this.game.playerProfile()
      };
      
      if (apiKey) reqBody.customKey = apiKey;
      
      const apiUrl = (this.auth as any).apiUrl;
      
      const res = await fetch(apiUrl + '/free-action', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          ...(token ? { 'Authorization': 'Bearer ' + token } : {})
        },
        body: JSON.stringify(reqBody)
      });
      
      if (!res.ok) throw new Error('Falha na resposta do servidor');
      const data = await res.json();
      
      const logsToAdd: string[] = [data.narrative || 'Nada acontece.'];
      
      if (data.sanityCost > 0) {
        this.game.takeSanityDamage(data.sanityCost);
        logsToAdd.push('[- ' + data.sanityCost + ' de Sanidade]');
      }
      if (data.staminaCost > 0) {
        this.game.drainStamina(data.staminaCost);
        logsToAdd.push('[- ' + data.staminaCost + ' de Fôlego]');
      }
      if (data.hpDamage > 0) {
        this.game.updateStats({ hp: Math.max(0, this.game.stats().hp - data.hpDamage) });
        logsToAdd.push('[- ' + data.hpDamage + ' de Vida]');
      }
      if (data.itemFound) {
        this.game.addToInventory(data.itemFound);
        logsToAdd.push('[+ Item obtido: ' + data.itemFound + ']');
      }
      if (data.itemLost) {
        this.game.removeFromInventory(data.itemLost);
        logsToAdd.push('[- Item perdido: ' + data.itemLost + ']');
      }
      if (data.hiddenPathFound && data.approved) {
        this.game.goToNode(data.hiddenPathFound);
      }

      this.narrativeLog.update(l => [...l, ...logsToAdd]);
    } catch (e) {
      this.narrativeLog.update(l => [...l, '[- O universo não respondeu à sua ação. (Erro de API)]']);
    } finally {
      this.isProcessingFreeAction.set(false);
    }
  }

  async handleDialogueChat(message: string) {
    const npcId = this.game.activeNpcDialogueId();
    if (!npcId) return;

    this.narrativeLog.update(l => [...l, '> ' + message]);
    this.isProcessingFreeAction.set(true);
    
    this.game.addDialogueMessage(npcId, { role: 'user', content: message });
    
    try {
      const token = this.auth.token();
      const apiKey = this.auth.customGeminiKey();
      const memory = this.game.npcMemories()[npcId];
      
      const reqBody: any = {
        npcId,
        message,
        gameContext: {
          currentNode: this.currentNode()?.location,
          playerStats: this.game.stats()
        },
        memoryContext: memory ? {
           summarizedContext: memory.summarizedContext,
           recentMessages: memory.recentMessages
        } : null
      };
      
      if (apiKey) reqBody.customApiKey = apiKey;
      
      const apiUrl = (this.auth as any).apiUrl;
      
      const res = await fetch(apiUrl + '/dialogue', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          ...(token ? { 'Authorization': 'Bearer ' + token } : {})
        },
        body: JSON.stringify(reqBody)
      });
      
      if (!res.ok) throw new Error('Falha no servidor');
      const data = await res.json();
      
      const npcName = npcProfiles[npcId]?.codinome || npcId;
      this.narrativeLog.update(l => [...l, npcName + ': ' + data.reply]);
      this.game.addDialogueMessage(npcId, { role: 'npc', content: data.reply });
      
      if (data.newSummarizedContext) {
        this.game.updateNpcMemory(npcId, data.newSummarizedContext);
      }
    } catch (e) {
       this.narrativeLog.update(l => [...l, '[- O NPC te ignora confusamente. (Erro de API)]']);
    } finally {
      this.isProcessingFreeAction.set(false);
    }
  }
}

// src/components/screens/GameScreen.tsx
'use client';

import { useState, useEffect, useRef } from 'react';
import StatusHUD from '../hud/StatusHUD';
import NarrativePanel from '../narrative/NarrativePanel';
import ActionPanel from '../actions/ActionPanel';
import AIThinkingOverlay from '../actions/AIThinkingOverlay';
import { useGameStore } from '../../store/gameStore';
import storyData from '../../data/storyData.json';
import Image from 'next/image';
import { StoryNode } from '../../types/game';
import { useAuthStore } from '../../store/authStore';
import OptionsScreen from './OptionsScreen';

const API_URL = process.env.NEXT_PUBLIC_API_URL || 'http://localhost:3001/api';
const MAX_FREE_ACTION_ATTEMPTS = 3;

interface GameScreenProps {
  onMenuClick: () => void;
}

export default function GameScreen({ onMenuClick }: GameScreenProps) {
  const { currentNodeId, goToNode, takeSanityDamage, drainStamina, addToInventory, removeFromInventory, stats, inventory, companion, playerProfile } = useGameStore();
  const { saveGame, customGeminiKey } = useAuthStore();
  const [node, setNode] = useState<StoryNode | null>(null);
  const [loading, setLoading] = useState(false);
  const [showOptionsModal, setShowOptionsModal] = useState(false);
  const [narrativeLog, setNarrativeLog] = useState<string[]>([]);
  const [freeActionAttempts, setFreeActionAttempts] = useState(0);
  const [isAIThinking, setIsAIThinking] = useState(false);
  
  // Track previous node to know when to save and reset attempts
  const prevNodeRef = useRef(currentNodeId);
  const benchmarkDoneRef = useRef(false);

  // Run model benchmark once on mount
  useEffect(() => {
    if (benchmarkDoneRef.current) return;
    benchmarkDoneRef.current = true;
    
    fetch(`${API_URL}/free-action/benchmark`)
      .then(res => res.json())
      .then(data => {
        console.log('[benchmark] Models sorted:', data.sortedOrder?.join(' → '));
      })
      .catch(err => {
        console.warn('[benchmark] Failed (will use default order):', err.message);
      });
  }, []);

  // Load current node data
  const nextNode = (storyData.nodes as Record<string, StoryNode>)[currentNodeId];
  if (nextNode && (!node || node.id !== nextNode.id)) {
    setNode(nextNode);
    setNarrativeLog([nextNode.baseDescription]);
  }

  // Auto-save when node changes + reset free action attempts
  useEffect(() => {
    if (prevNodeRef.current !== currentNodeId) {
      prevNodeRef.current = currentNodeId;
      setFreeActionAttempts(0); // Reset attempts on node change
      const state = useGameStore.getState();
      saveGame(state);
    }
  }, [currentNodeId, saveGame]);

  const handleOptionClick = (nextId: string) => {
    if (isAIThinking) return; // Block during AI processing
    goToNode(nextId);
  };

  const handleFreeAction = async (text: string) => {
    if (freeActionAttempts >= MAX_FREE_ACTION_ATTEMPTS || isAIThinking) return;

    setLoading(true);
    setIsAIThinking(true);
    setFreeActionAttempts(prev => prev + 1);

    try {
      const response = await fetch(`${API_URL}/free-action`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          action: text,
          nodeContext: node,
          playerStats: stats,
          inventory,
          companion,
          customKey: customGeminiKey,
          playerProfile,
        }),
      });

      const result = await response.json();

      // Add action attempt to narrative
      setNarrativeLog(prev => [
        ...prev,
        `> ${text}`,
        result.narrative,
      ]);

      // Apply stat effects
      if (result.sanityCost > 0) {
        takeSanityDamage(result.sanityCost);
        setNarrativeLog(prev => [
          ...prev,
          `[-${result.sanityCost} Sanidade]`,
        ]);
      }
      if (result.staminaCost > 0) {
        drainStamina(result.staminaCost);
        setNarrativeLog(prev => [
          ...prev,
          `[-${result.staminaCost} Stamina]`,
        ]);
      }

      // Handle inventory changes
      if (result.itemFound) {
        addToInventory(result.itemFound);
        setNarrativeLog(prev => [
          ...prev,
          `[Item obtido: ${result.itemFound}]`,
        ]);
      }
      if (result.itemLost) {
        removeFromInventory(result.itemLost);
        setNarrativeLog(prev => [
          ...prev,
          `[Item perdido: ${result.itemLost}]`,
        ]);
      }

      // Handle hidden path discovery
      if (result.hiddenPathFound) {
        const hiddenNodeExists = (storyData.nodes as Record<string, StoryNode>)[result.hiddenPathFound];
        if (hiddenNodeExists) {
          setTimeout(() => {
            goToNode(result.hiddenPathFound);
          }, 3000);
          setNarrativeLog(prev => [
            ...prev,
            '[Um novo caminho se revela...]',
          ]);
        }
      }
    } catch (err) {
      console.error('Free action error:', err);
      setNarrativeLog(prev => [
        ...prev,
        `> ${text}`,
        'Um silêncio opressivo responde à sua tentativa. Algo no ar parece resistir. Tente outra coisa.',
      ]);
      takeSanityDamage(2);
    } finally {
      setLoading(false);
      setIsAIThinking(false);
    }
  };

  if (!node) return <div className="p-8 text-white flex items-center justify-center h-full">Carregando dados da realidade...</div>;

  const locationSlug = node.location
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .toLowerCase()
    .replace(/\s+/g, '-');
  const locationImageSrc = node.image ? `/assets/locations/${node.image}` : `/assets/locations/${locationSlug}.png`;

  return (
    <div className="w-full h-full relative font-mono text-gray-300 left-30">
      
      {/* AI Thinking Overlay — blocks all interaction */}
      {isAIThinking && <AIThinkingOverlay />}
      
      {/* Options Overlay */}
      {showOptionsModal && (
        <OptionsScreen 
          isOverlay 
          onBack={() => setShowOptionsModal(false)} 
        />
      )}

      {/* Top Controls */}
      <div className="absolute top-4 right-6 z-50 flex gap-4">
        <button 
          onClick={() => setShowOptionsModal(true)}
          disabled={isAIThinking}
          className="bg-[#2d372b]/80 border-2 border-[#495845] px-4 py-2 text-xs uppercase tracking-widest hover:bg-[#495845] hover:text-white transition-colors disabled:opacity-50 disabled:pointer-events-none"
        >
          [ CFG ] Opções
        </button>
        <button 
          onClick={onMenuClick}
          disabled={isAIThinking}
          className="bg-[#2d372b]/80 border-2 border-[#495845] px-4 py-2 text-xs uppercase tracking-widest hover:bg-[#495845] hover:text-white transition-colors disabled:opacity-50 disabled:pointer-events-none"
        >
          [ ESC ] Sair
        </button>
      </div>

      {/* Top Left: HUDs */}
      <div className="absolute top-4 left-6 z-50">
        <StatusHUD />
      </div>

      {/* Main Content Area: Scene + Text */}
      <div className="absolute top-[15vh] left-6 bottom-[15vh] w-[75vw] max-w-[1400px] flex items-stretch z-10">
        
        {/* Left Panel: Scene Image */}
        <div className="hidden md:block w-[45%] border-[4px] border-[#2b3028] border-r-0 bg-[#0d0f0c] shadow-2xl relative overflow-hidden shrink-0">
          <div className="absolute inset-0 bg-[#2d372b]/20 flex flex-col items-center justify-center text-[#495845] font-bold text-xl uppercase tracking-widest text-center px-4">
            <span>[Cena do Local]</span>
            <span className="text-sm mt-2 opacity-50">{node.location}</span>
          </div>

          <Image 
            src={locationImageSrc} 
            alt={node.location} 
            fill
            sizes="(max-width: 768px) 100vw, 45vw"
            className="object-cover z-10"
            style={{ imageRendering: 'pixelated' }}
            onError={(e) => { e.currentTarget.style.display = 'none'; }}
            onLoad={(e) => { e.currentTarget.style.display = 'block'; }}
          />
        </div>

        {/* Center Panel: Narrative and Actions */}
        <div className="flex-1 flex flex-col bg-[#161815]/95 border-[4px] border-[#2b3028] shadow-2xl relative backdrop-blur-sm min-w-[500px]">
          <NarrativePanel
            location={node.location}
            narrativeLog={narrativeLog}
          />

          <ActionPanel
            options={node.options}
            allowFourthOption={node.allowFourthOption}
            loading={loading}
            onOptionClick={handleOptionClick}
            onFreeAction={handleFreeAction}
            freeActionAttemptsRemaining={MAX_FREE_ACTION_ATTEMPTS - freeActionAttempts}
            freeActionMaxAttempts={MAX_FREE_ACTION_ATTEMPTS}
          />
        </div>
      </div>

      {/* Bottom Right: Character Full Body Sprites */}
      <div className="absolute bottom-0 right-[5%] z-20 pointer-events-none h-[50vh] flex gap-4 items-end">
        {node.npcsPresentes?.includes('mecanica') && (
          <div className="relative h-full w-[30vh]">
            <Image 
              src="/assets/characters/mecanica/body.png" 
              alt="Mecânica" 
              fill
              sizes="30vh"
              className="object-contain object-bottom drop-shadow-2xl opacity-90"
              style={{ imageRendering: 'pixelated' }}
            />
          </div>
        )}
        {(node.npcsPresentes?.includes('muro') || node.npcsPresentes?.includes('ed_fisica')) && (
          <div className="relative h-full w-[30vh]">
            <Image 
              src="/assets/characters/muro/body.png" 
              alt="Muro" 
              fill
              sizes="30vh"
              className="object-contain object-bottom drop-shadow-2xl opacity-90"
              style={{ imageRendering: 'pixelated' }}
            />
          </div>
        )}
      </div>

    </div>
  );
}
