// src/app/app.component.ts
import { Component, computed, inject, signal, OnInit } from '@angular/core';
import { GameService } from './services/game.service';
import { AuthService } from './services/auth.service';
import { LoginScreenComponent } from './components/screens/login-screen.component';
import { MenuScreenComponent } from './components/screens/menu-screen.component';
import { CharacterCreationScreenComponent } from './components/screens/character-creation-screen.component';
import { GameScreenComponent } from './components/screens/game-screen.component';
import { DeathScreenComponent } from './components/screens/death-screen.component';
import { CutsceneEngineComponent } from './components/cutscene/cutscene-engine.component';
import { introCutscene } from './data/cutscenes/intro';

type ScreenState = 'login' | 'menu' | 'options' | 'character-creation' | 'intro' | 'game' | 'death';

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [
    LoginScreenComponent,
    MenuScreenComponent,
    CharacterCreationScreenComponent,
    GameScreenComponent,
    DeathScreenComponent,
    CutsceneEngineComponent
  ],
  template: `
    @if (isInitializing()) {
      <div class="w-full h-full flex items-center justify-center bg-[#0d0f0c] text-terminal-green font-mono crt-flicker">
        Inicializando Sistema...
      </div>
    } @else if (auth.isLoading() && currentScreen() !== 'login') {
      <div class="w-full h-full flex items-center justify-center bg-[#0d0f0c] text-terminal-green font-mono crt-flicker">
        Sincronizando com o terminal central...
      </div>
    } @else {
      @switch (currentScreen()) {
        @case ('login') {
          <app-login-screen class="block w-full h-full" (loginSuccess)="handleLoginSuccess()" />
        }
        @case ('menu') {
          <app-menu-screen 
            class="block w-full h-full"
            (onPlayClick)="handlePlayClick()"
            (onOptionsClick)="handleOptionsClick()"
          />
        }
        @case ('character-creation') {
          <app-character-creation-screen class="block w-full h-full" (characterCreated)="handleCharacterCreationComplete()" />
        }
        @case ('intro') {
          <app-cutscene-engine
            class="block w-full h-full"
            [cutscene]="introCutscene"
            (cutsceneComplete)="handleCutsceneComplete()"
          />
        }
        @case ('game') {
          <app-game-screen class="block w-full h-full" (returnToMenu)="localScreen.set('menu')" />
        }
        @case ('death') {
          <app-death-screen class="block w-full h-full" (returnToMenu)="localScreen.set('menu')" />
        }
        @case ('options') {
           <!-- TODO: OptionsScreen not fully migrated yet, fallback to menu -->
          <div class="w-full h-full flex items-center justify-center bg-black text-white cursor-pointer" (click)="localScreen.set('menu')">
            [ OPÇÕES INDISPONÍVEIS NA MIGRAÇÃO ATUAL - CLIQUE PARA VOLTAR ]
          </div>
        }
      }
    }
  `,
})
export class AppComponent implements OnInit {
  readonly game = inject(GameService);
  readonly auth = inject(AuthService);
  readonly introCutscene = introCutscene;

  readonly isInitializing = signal(true);
  readonly localScreen = signal<ScreenState>('login');

  readonly currentScreen = computed<ScreenState>(() => {
    // Override por morte
    if (this.game.stats().hp <= 0 && this.game.currentNodeId() !== 'cap1_republica_start') {
      return 'death';
    }

    if (!this.auth.isAuthenticated() && this.localScreen() !== 'login') {
      return 'login';
    }
    if (this.auth.isAuthenticated() && this.localScreen() === 'login') {
      return 'menu';
    }
    
    return this.localScreen();
  });

  ngOnInit() {
    this.isInitializing.set(false);
  }

  handleLoginSuccess() {
    this.localScreen.set('menu');
  }

  async handlePlayClick() {
    const savedState = await this.auth.loadGame();
    if (savedState) {
      this.game.loadState(savedState);
      
      if (!this.game.hasCreatedCharacter()) {
        this.localScreen.set('character-creation');
      } else if (!this.game.hasSeenIntroCutscene()) {
        this.localScreen.set('intro');
      } else {
        this.localScreen.set('game');
      }
    } else {
      // Novo jogo
      this.game.resetToInitialState();
      this.localScreen.set('character-creation');
    }
  }

  handleOptionsClick() {
    this.localScreen.set('options');
  }

  handleCharacterCreationComplete() {
    if (!this.game.hasSeenIntroCutscene()) {
      this.localScreen.set('intro');
    } else {
      this.localScreen.set('game');
    }
  }

  handleCutsceneComplete() {
    this.game.setHasSeenIntroCutscene(true);
    this.localScreen.set('game');
  }
}

// src/app/page.tsx
'use client';

import { useState, useEffect } from 'react';
import { useAuthStore } from '../store/authStore';
import { useGameStore } from '../store/gameStore';
import LoginScreen from '../components/screens/LoginScreen';
import MenuScreen from '../components/screens/MenuScreen';
import OptionsScreen from '../components/screens/OptionsScreen';
import GameScreen from '../components/screens/GameScreen';
import CharacterCreationScreen from '../components/screens/CharacterCreationScreen';
import CutscenePlayer from '../components/cutscene/CutscenePlayer';
import { introCutscene } from '../data/cutscenes/intro';

type ScreenType = 'login' | 'menu' | 'options' | 'game' | 'cutscene' | 'character-creation';

export default function AppOrchestrator() {
  const { isAuthenticated, loadGame, isLoading } = useAuthStore();
  const [currentScreen, setCurrentScreen] = useState<ScreenType>('login');
  const [isInitializing, setIsInitializing] = useState(true);

  // Sync route with authentication status
  useEffect(() => {
    // eslint-disable-next-line react-hooks/set-state-in-effect
    setIsInitializing(false);
  }, []);

  let displayedScreen = currentScreen;
  if (!isInitializing) {
    if (isAuthenticated && currentScreen === 'login') {
      displayedScreen = 'menu';
    } else if (!isAuthenticated && currentScreen !== 'login') {
      displayedScreen = 'login';
    }
  }

  const handleLoginSuccess = () => {
    setCurrentScreen('menu');
  };

  const handlePlayClick = async () => {
    // Tenta carregar o save do backend antes de iniciar
    const savedState = await loadGame();
    if (savedState) {
      useGameStore.setState(savedState);
      
      if (!savedState.hasCreatedCharacter) {
        setCurrentScreen('character-creation');
      } else if (!savedState.hasSeenIntroCutscene) {
        setCurrentScreen('cutscene');
      } else {
        setCurrentScreen('game');
      }
    } else {
      // Novo jogo
      setCurrentScreen('character-creation');
    }
  };

  const handleCharacterCreationComplete = () => {
    // Após criar o personagem, vai pra cutscene inicial se não viu
    if (!useGameStore.getState().hasSeenIntroCutscene) {
      setCurrentScreen('cutscene');
    } else {
      setCurrentScreen('game');
    }
  };

  const handleCutsceneComplete = () => {
    useGameStore.getState().setHasSeenIntroCutscene(true);
    setCurrentScreen('game');
  };

  if (isInitializing) {
    return (
      <div className="w-full h-full flex items-center justify-center bg-[#0d0f0c] text-[#4ade80] font-mono crt-flicker">
        Inicializando Sistema...
      </div>
    );
  }

  // Se está carregando dados (ex: fazendo login)
  if (isLoading && currentScreen !== 'login') {
     return (
      <div className="w-full h-full flex items-center justify-center bg-[#0d0f0c] text-[#4ade80] font-mono crt-flicker">
        Sincronizando com o terminal central...
      </div>
    );
  }

  // Render the current screen
  switch (displayedScreen) {
    case 'login':
      return <LoginScreen onLoginSuccess={handleLoginSuccess} />;
    case 'menu':
      return (
        <MenuScreen 
          onPlayClick={handlePlayClick} 
          onOptionsClick={() => setCurrentScreen('options')} 
        />
      );
    case 'options':
      return <OptionsScreen onBack={() => setCurrentScreen('menu')} />;
    case 'character-creation':
      return <CharacterCreationScreen onComplete={handleCharacterCreationComplete} />;
    case 'game':
      return <GameScreen onMenuClick={() => setCurrentScreen('menu')} />;
    case 'cutscene':
      return <CutscenePlayer data={introCutscene} onComplete={handleCutsceneComplete} />;
    default:
      return <LoginScreen onLoginSuccess={handleLoginSuccess} />;
  }
}
