// src/components/actions/OptionButton.tsx
'use client';

import { StoryOption } from '../../types/game';

/**
 * OptionButton — A single story option rendered as a styled button.
 *
 * Single Responsibility: renders one option button.
 * Interface Segregation: only needs the option data + click handler.
 */

interface OptionButtonProps {
  option: StoryOption;
  onClick: (nextId: string) => void;
}

export default function OptionButton({ option, onClick }: OptionButtonProps) {
  return (
    <button
      onClick={() => onClick(option.nextId ?? option.id)}
      className="text-left px-4 py-2 border border-[#495845] hover:bg-[#2d372b] hover:text-white transition-colors uppercase text-xs sm:text-sm flex items-center gap-2"
    >
      <span className="text-terminal-green font-bold">[{option.id}]</span>
      {option.text}
    </button>
  );
}

// src/app/components/actions/option-button.component.ts
import { Component, input, output } from '@angular/core';
import { StoryOption } from '../../types/game';

@Component({
  selector: 'app-option-button',
  standalone: true,
  template: `
    <button
      (click)="optionClick.emit(option().nextId ?? option().id)"
      class="text-left px-3 py-1.5 border border-[#495845] hover:bg-[#2d372b] hover:text-white transition-colors uppercase text-xs flex items-center gap-2 font-mono"
    >
      <span class="text-terminal-green font-bold">[{{ option().id }}]</span>
      {{ option().text }}
    </button>
  `,
})
export class OptionButtonComponent {
  readonly option = input.required<StoryOption>();
  readonly optionClick = output<string>();
}
